INSERT INTO nauczyciel (imie, nazwisko) VALUES
  ('Paulina', 'Sobczak'),
  ('Henryk', 'Bąk'),
  ('Kazimierz', 'Górski'),
  ('Irena', 'Wójcik'),
  ('Marian', 'Chmielewski'),
  ('Małgorzata', 'Jaworska'),
  ('Ewa', 'Duda'),
  ('Jakub', 'Malinowski'),
  ('Jadwiga', 'Brzezińska'),
  ('Roman', 'Sawicki');

INSERT INTO klasa (nazwa, id_wychowawca) VALUES
  ('1A', 5),
  ('1B', 4),
  ('2A', 3),
  ('2B', 7),
  ('3A', 8),
  ('3B', 1);

INSERT INTO uczen (id_klasa, imie, nazwisko) VALUES
  (1, 'Marcin', 'Szymczak'),
  (1, 'Joanna', 'Baranowska'),
  (1, 'Maciej', 'Szczepański'),
  (1, 'Czesław', 'Wróbel'),
  (1, 'Grażyna', 'Górska'),
  (1, 'Wanda', 'Krawczyk'),
  (1, 'Renata', 'Urbańska'),
  (1, 'Wiesława', 'Tomaszewska'),
  (1, 'Bożena', 'Baranowska'),
  (1, 'Ewelina', 'Malinowska'),
  (1, 'Anna', 'Krajewska'),
  (1, 'Mieczysław', 'Zając'),
  (1, 'Wiesław', 'Przybylski'),
  (1, 'Dorota', 'Tomaszewska'),
  (1, 'Jerzy', 'Wróblewski'),
  (2, 'Magdalena', 'Adamczyk'),
  (2, 'Władysław', 'Piotrowski'),
  (2, 'Marek', 'Wiśniewski'),
  (2, 'Stanisława', 'Głowacka'),
  (2, 'Agata', 'Kubiak'),
  (2, 'Marian', 'Kowalski'),
  (2, 'Piotr', 'Szymański'),
  (2, 'Stanisław', 'Kowalski'),
  (2, 'Aleksandra', 'Szulc'),
  (2, 'Tomasz', 'Kucharski'),
  (2, 'Marcin', 'Mazurek'),
  (2, 'Sebastian', 'Baranowski'),
  (2, 'Agata', 'Wysocka'),
  (2, 'Grażyna', 'Mazur'),
  (2, 'Marcin', 'Gajewski'),
  (3, 'Krystyna', 'Sikorska'),
  (3, 'Krzysztof', 'Kowalski'),
  (3, 'Małgorzata', 'Mazurek'),
  (3, 'Adam', 'Jasiński'),
  (3, 'Patrycja', 'Makowska'),
  (3, 'Piotr', 'Adamczyk'),
  (3, 'Waldemar', 'Wieczorek'),
  (3, 'Edward', 'Szulc'),
  (3, 'Janusz', 'Andrzejewski'),
  (3, 'Edyta', 'Nowakowska'),
  (3, 'Joanna', 'Woźniak'),
  (3, 'Mateusz', 'Michalak'),
  (3, 'Marta', 'Sobczak'),
  (3, 'Waldemar', 'Makowski'),
  (3, 'Marzena', 'Jabłońska'),
  (4, 'Maciej', 'Sikora'),
  (4, 'Monika', 'Szewczyk'),
  (4, 'Genowefa', 'Cieślak'),
  (4, 'Edyta', 'Nowicka'),
  (4, 'Piotr', 'Malinowski'),
  (4, 'Krzysztof', 'Głowacki'),
  (4, 'Andrzej', 'Szewczyk'),
  (4, 'Mariusz', 'Grabowski'),
  (4, 'Stefania', 'Król'),
  (4, 'Wiesław', 'Szczepański'),
  (4, 'Małgorzata', 'Wasilewska'),
  (4, 'Józef', 'Szczepański'),
  (4, 'Mariusz', 'Kowalczyk'),
  (4, 'Janina', 'Kozłowska'),
  (4, 'Roman', 'Kwiatkowski'),
  (5, 'Jadwiga', 'Kamińska'),
  (5, 'Agnieszka', 'Zając'),
  (5, 'Robert', 'Włodarczyk'),
  (5, 'Henryk', 'Kowalski'),
  (5, 'Kazimiera', 'Zalewska'),
  (5, 'Sylwia', 'Kaźmierczak'),
  (5, 'Dorota', 'Maciejewska'),
  (5, 'Jacek', 'Laskowski'),
  (5, 'Michał', 'Sobczak'),
  (5, 'Genowefa', 'Lis'),
  (5, 'Mirosław', 'Czerwiński'),
  (5, 'Agata', 'Gajewska'),
  (5, 'Zofia', 'Bąk'),
  (5, 'Marek', 'Adamczyk'),
  (5, 'Agata', 'Pawlak'),
  (6, 'Adam', 'Jankowski'),
  (6, 'Mieczysław', 'Adamczyk'),
  (6, 'Wanda', 'Czarnecka'),
  (6, 'Andrzej', 'Ziółkowski'),
  (6, 'Jarosław', 'Laskowski'),
  (6, 'Iwona', 'Urbańska'),
  (6, 'Aneta', 'Jakubowska'),
  (6, 'Zdzisław', 'Król'),
  (6, 'Maria', 'Wiśniewska'),
  (6, 'Grzegorz', 'Borkowski'),
  (6, 'Maria', 'Głowacka'),
  (6, 'Jakub', 'Pietrzak'),
  (6, 'Danuta', 'Piotrowska'),
  (6, 'Sebastian', 'Chmielewski'),
  (6, 'Adam', 'Andrzejewski');

INSERT INTO przedmioty(nazwa) VALUES
  ('Język polski'),
  ('Język angielski'),
  ('Matematyka'),
  ('Historia'),
  ('Geografia'),
  ('Biologia'),
  ('Fizyka'),
  ('Wychowanie fizyczne');

INSERT INTO sale(numer) VALUES
  ('1'), ('2'), ('3'), ('4'), ('5'), ('6'), ('7'), ('Sala gimnastyczna');